-module(consumer_group_heartbeat_response).
-export([
    encode_consumer_group_heartbeat_response_0/1,
    decode_consumer_group_heartbeat_response_0/1
]).
-export_type([
    consumer_group_heartbeat_response_0/0,
    assignment_0/0,
    topic_partitions_0/0
]).
-include("../encoders.hrl").
-include("../decoders.hrl").
-include("../guards.hrl").
-include("../error.hrl").

-define(EMPTY_TAG_BUFFER, [<<0:8/big>>]).

-spec encode_consumer_group_heartbeat_response_0(consumer_group_heartbeat_response_0()) -> iodata().

encode_consumer_group_heartbeat_response_0(
    _Args = #{
        % The correlation ID of this request.
        correlation_id := CorrelationId,
        % The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
        throttle_time_ms := ThrottleTimeMs,
        % The top-level error code, or 0 if there was no error
        error_code := ErrorCode,
        % The top-level error message, or null if there was no error.
        error_message := ErrorMessage,
        % The member id generated by the coordinator. Only provided when the member joins with MemberEpoch == 0.
        member_id := MemberId,
        % The member epoch.
        member_epoch := MemberEpoch,
        % The heartbeat interval in milliseconds.
        heartbeat_interval_ms := HeartbeatIntervalMs,
        % null if not provided; the assignment otherwise.
        assignment := Assignment
    }
) when
    ?is_int32(CorrelationId),
    ?is_int32(ThrottleTimeMs),
    ?is_int16(ErrorCode),
    ?is_nullable_string(ErrorMessage),
    ?is_nullable_string(MemberId),
    ?is_int32(MemberEpoch),
    ?is_int32(HeartbeatIntervalMs),
    ?is_nullable_entity(Assignment)
->
    [
        ?encode_response_header_1(CorrelationId),
        ?encode_int32(ThrottleTimeMs),
        ?encode_int16(ErrorCode),
        ?encode_compact_nullable_string(ErrorMessage),
        ?encode_compact_nullable_string(MemberId),
        ?encode_int32(MemberEpoch),
        ?encode_int32(HeartbeatIntervalMs),
        encode_assignment_0(Assignment),
        ?EMPTY_TAG_BUFFER
    ];
encode_consumer_group_heartbeat_response_0(Args) ->
    ?encoder_error(Args, #{
        correlation_id => int32,
        throttle_time_ms => int32,
        error_code => int16,
        error_message => nullable_string,
        member_id => nullable_string,
        member_epoch => int32,
        heartbeat_interval_ms => int32,
        assignment => nullable_Assignment
    }).

-spec decode_consumer_group_heartbeat_response_0(binary()) -> {Decoded, Rest} when
    Decoded :: consumer_group_heartbeat_response_0(),
    Rest :: binary().

decode_consumer_group_heartbeat_response_0(Bin) when is_binary(Bin) ->
    {Header, Bin0} = ?decode_response_header_1(Bin),
    ?_decode_int32(ThrottleTimeMs, Bin0, Bin1),
    ?_decode_int16(ErrorCode, Bin1, Bin2),
    ?_decode_compact_nullable_string(ErrorMessage, Bin2, Bin3),
    ?_decode_compact_nullable_string(MemberId, Bin3, Bin4),
    ?_decode_int32(MemberEpoch, Bin4, Bin5),
    ?_decode_int32(HeartbeatIntervalMs, Bin5, Bin6),
    ?_decode_entity(Assignment, Bin6, Bin7, decode_assignment_0),
    ?decode_tagged_fields(
        fun decode_consumer_group_heartbeat_response_0_tagged_field/3,
        Header#{
            throttle_time_ms => ThrottleTimeMs,
            error_code => ErrorCode,
            error_message => ErrorMessage,
            member_id => MemberId,
            member_epoch => MemberEpoch,
            heartbeat_interval_ms => HeartbeatIntervalMs,
            assignment => Assignment
        },
        Bin7
    ).

-spec decode_consumer_group_heartbeat_response_0_tagged_field(Tag, Input, AccIn) -> AccOut when
    Tag :: non_neg_integer(),
    Input :: binary(),
    AccIn :: Acc,
    AccOut :: Acc,
    Acc :: consumer_group_heartbeat_response_0().

decode_consumer_group_heartbeat_response_0_tagged_field(_Tag, _Bin0, Acc) ->
    % Unrecognised tag; ignore it.
    Acc.

-spec encode_assignment_0(assignment_0()) -> iodata().

encode_assignment_0(
    _Args = #{
        % The partitions assigned to the member that can be used immediately.
        topic_partitions := TopicPartitions
    }
) when
    ?is_array(TopicPartitions)
->
    [
        ?encode_compact_array(TopicPartitions, fun encode_topic_partitions_0/1),
        ?EMPTY_TAG_BUFFER
    ];
encode_assignment_0(Args) ->
    ?encoder_error(Args, #{
        topic_partitions => {array, topic_partitions_0}
    }).

-spec decode_assignment_0(binary()) -> {Decoded, Rest} when
    Decoded :: assignment_0(),
    Rest :: binary().

decode_assignment_0(Bin0) when is_binary(Bin0) ->
    ?_decode_compact_array(TopicPartitions, Bin0, Bin1, ?_decode_element(decode_topic_partitions_0)),
    ?decode_tagged_fields(
        fun decode_assignment_0_tagged_field/3,
        #{
            topic_partitions => TopicPartitions
        },
        Bin1
    ).

-spec decode_assignment_0_tagged_field(Tag, Input, AccIn) -> AccOut when
    Tag :: non_neg_integer(),
    Input :: binary(),
    AccIn :: Acc,
    AccOut :: Acc,
    Acc :: assignment_0().

decode_assignment_0_tagged_field(_Tag, _Bin0, Acc) ->
    % Unrecognised tag; ignore it.
    Acc.

-spec encode_topic_partitions_0(topic_partitions_0()) -> iodata().

encode_topic_partitions_0(
    _Args = #{
        % The topic ID.
        topic_id := TopicId,
        % The partitions.
        partitions := Partitions
    }
) when
    ?is_uuid(TopicId),
    ?is_array(Partitions)
->
    [
        ?encode_uuid(TopicId),
        ?encode_compact_array(Partitions, ?encode_int32_),
        ?EMPTY_TAG_BUFFER
    ];
encode_topic_partitions_0(Args) ->
    ?encoder_error(Args, #{
        topic_id => uuid,
        partitions => {array, int32}
    }).

-spec decode_topic_partitions_0(binary()) -> {Decoded, Rest} when
    Decoded :: topic_partitions_0(),
    Rest :: binary().

decode_topic_partitions_0(Bin0) when is_binary(Bin0) ->
    ?_decode_uuid(TopicId, Bin0, Bin1),
    ?_decode_compact_array(Partitions, Bin1, Bin2, ?decode_int32_),
    ?decode_tagged_fields(
        fun decode_topic_partitions_0_tagged_field/3,
        #{
            topic_id => TopicId,
            partitions => Partitions
        },
        Bin2
    ).

-spec decode_topic_partitions_0_tagged_field(Tag, Input, AccIn) -> AccOut when
    Tag :: non_neg_integer(),
    Input :: binary(),
    AccIn :: Acc,
    AccOut :: Acc,
    Acc :: topic_partitions_0().

decode_topic_partitions_0_tagged_field(_Tag, _Bin0, Acc) ->
    % Unrecognised tag; ignore it.
    Acc.

-type consumer_group_heartbeat_response_0() :: #{
    correlation_id => integer(),
    throttle_time_ms := integer(),
    error_code := integer(),
    error_message := binary() | null,
    member_id := binary() | null,
    member_epoch := integer(),
    heartbeat_interval_ms := integer(),
    assignment := assignment_0() | null
}.
-type assignment_0() :: #{
    topic_partitions := list(topic_partitions_0())
}.
-type topic_partitions_0() :: #{
    topic_id := kafcod:uuid(),
    partitions := list(integer())
}.
